"""
brief_ui.py
-----------
Drop-in Streamlit UI component for the LLM analyst brief.

Imports the brief generator and renders the button, gating controls,
and the four-section tabbed output. Styling matches the Readout design
system (light/clinical, teal accent, Inter typography).
"""

from datetime import datetime

import streamlit as st
from generate_brief import generate_analyst_brief


def _build_markdown_export(brief: dict, filters: dict) -> str:
    """Format the brief and filter context as a portable Markdown document."""

    ta = filters.get("therapeutic_area", "All")
    phases = filters.get("phases", []) or []
    year_range = filters.get("year_range", ("—", "—"))
    sponsor_type = filters.get("sponsor_type", []) or []

    # Convert phase codes to readable labels for the export
    phase_label_map = {
        "EARLY_PHASE1": "Early Phase 1", "PHASE1": "Phase 1",
        "PHASE1_PHASE2": "Phase 1/2", "PHASE2": "Phase 2",
        "PHASE2_PHASE3": "Phase 2/3", "PHASE3": "Phase 3", "PHASE4": "Phase 4",
    }
    phases_readable = ", ".join(phase_label_map.get(p, p) for p in phases) if phases else "All phases"
    sponsor_readable = ", ".join(sponsor_type) if sponsor_type else "All sponsor types"

    timestamp = datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")

    md = f"""# Readout | AI Analyst Brief

**Therapeutic Area:** {ta}
**Phase Selection:** {phases_readable}
**Year Range:** {year_range[0]}–{year_range[1]}
**Sponsor Type:** {sponsor_readable}
**Generated:** {timestamp}

---

## Pipeline Summary

{brief.get('pipeline_summary', '')}

## Competitive Landscape

{brief.get('competitive_landscape', '')}

## Key Signals

{brief.get('key_signals', '')}

## Takeaway

{brief.get('takeaway', '')}

---

*Generated by Claude (claude-sonnet-4-6) from filtered ClinicalTrials.gov + openFDA data. Not for clinical decision-making.*

*Source: [Readout](https://readout.streamlit.app)*
"""
    return md


def render_brief_section(df_filtered, filters: dict):
    """
    Renders the Generate Brief button and tabbed brief output.

    Args:
        df_filtered: The filtered DataFrame used to render charts above
        filters: Dict of active filter values from the sidebar
    """

    # ── Constants ──────────────────────────────────────────────────────────
    SESSION_LIMIT = 3       # max brief generations per user session
    DATASET_ROW_CAP = 500   # rows passed to context builder

    # ── Section header (matches existing .section-label pattern) ───────────
    st.markdown(
        "<div class='section-label'>AI Analyst Brief</div>",
        unsafe_allow_html=True,
    )

    st.markdown(
        """
        <p style="color:#64748b; font-size:0.82rem; line-height:1.55;
                  margin-top:-0.5rem; margin-bottom:1rem; max-width:680px;">
            A competitive intelligence brief synthesized from the filtered dataset above, powered by Claude · Estimated delivery: 5–10 secs.
        </p>
        """,
        unsafe_allow_html=True,
    )

    # ── Kill switch ────────────────────────────────────────────────────────
    if not st.secrets.get("BRIEF_ENABLED", True):
        st.info("Brief generation is temporarily unavailable.")
        return

    # ── No data guard ──────────────────────────────────────────────────────
    if df_filtered is None or len(df_filtered) == 0:
        st.info("Apply filters above to enable brief generation.")
        return

    # ── Session-based rate limit ───────────────────────────────────────────
    if "brief_count" not in st.session_state:
        st.session_state.brief_count = 0

    remaining = SESSION_LIMIT - st.session_state.brief_count

    if remaining <= 0:
        st.warning(
            f"You've used all {SESSION_LIMIT} brief generations for this session. "
            "Refresh the page to start a new session."
        )
        return

    # ── Button + remaining-count caption, on one row ──────────────────────
    btn_col, count_col = st.columns([1, 4])
    with btn_col:
        clicked = st.button(
            "Generate Brief",
            type="primary",
            help="Calls the Claude API to synthesize a competitive intelligence brief from the current filtered view.",
            use_container_width=True,
        )
    with count_col:
        if st.session_state.brief_count > 0:
            st.markdown(
                f"<div style='padding-top:0.55rem; color:#64748b; "
                f"font-size:0.78rem; font-family:IBM Plex Mono, monospace;'>"
                f"{remaining} of {SESSION_LIMIT} remaining this session"
                f"</div>",
                unsafe_allow_html=True,
            )

    if clicked:
        # ── Run the brief ──────────────────────────────────────────────────
        df_for_brief = (
            df_filtered.sample(n=DATASET_ROW_CAP, random_state=42)
            if len(df_filtered) > DATASET_ROW_CAP
            else df_filtered
        )

        with st.spinner("Synthesizing analyst brief…"):
            api_key = st.secrets.get("ANTHROPIC_API_KEY", None)
            brief = generate_analyst_brief(df_for_brief, filters, api_key=api_key)

        st.session_state.brief_count += 1
        st.session_state.last_brief = brief
        st.session_state.last_brief_filters = filters

    # ── If no brief has been generated yet this session, stop here ─────────
    brief = st.session_state.get("last_brief")
    if brief is None:
        return

    if brief.get("error"):
        st.error(brief["error"])
        return

    # ── Tabbed output ──────────────────────────────────────────────────────
    card_style = (
        "background:#ffffff; border:1px solid #d1dae2; border-radius:8px; "
        "padding:1.25rem 1.5rem; color:#1a2332; line-height:1.65; "
        "font-size:0.9rem; margin-top:0.75rem;"
    )

    takeaway_style = (
        "background:#f0fdfa; border-left:3px solid #0d9488; "
        "border-radius:0 8px 8px 0; padding:1.25rem 1.5rem; "
        "color:#1a2332; line-height:1.7; font-size:0.93rem; margin-top:0.75rem;"
    )

    tab_summary, tab_competitive, tab_signals, tab_takeaway, tab_export = st.tabs([
        "Pipeline Summary",
        "Competitive Landscape",
        "Key Signals",
        "Takeaway",
        "Export",
    ])

    with tab_summary:
        st.markdown(
            f"<div style='{card_style}'>{brief['pipeline_summary']}</div>",
            unsafe_allow_html=True,
        )

    with tab_competitive:
        st.markdown(
            f"<div style='{card_style}'>{brief['competitive_landscape']}</div>",
            unsafe_allow_html=True,
        )

    with tab_signals:
        st.markdown(
            f"<div style='{card_style}'>{brief['key_signals']}</div>",
            unsafe_allow_html=True,
        )

    with tab_takeaway:
        st.markdown(
            f"<div style='{takeaway_style}'>{brief['takeaway']}</div>",
            unsafe_allow_html=True,
        )

    with tab_export:
        # Use the filters that produced THIS brief, not the live sidebar state
        export_filters = st.session_state.get("last_brief_filters", filters)
        markdown_blob = _build_markdown_export(brief, export_filters)

        # Filename includes therapeutic area + timestamp for portability
        ta_slug = (
            export_filters.get("therapeutic_area", "brief")
            .lower()
            .replace(" ", "-")
        )
        timestamp = datetime.utcnow().strftime("%Y%m%d-%H%M")
        filename = f"readout-{ta_slug}-{timestamp}.md"

        st.markdown(
            f"<div style='{card_style} margin-bottom:0.75rem;'>"
            f"Download the brief in Markdown (.md) format for use in Notion, Google Docs, Slack, email, or any text editor."
            f"</div>",
            unsafe_allow_html=True,
        )

        st.download_button(
            label="Download Brief (.md)",
            data=markdown_blob,
            file_name=filename,
            mime="text/markdown",
            type="primary",
            use_container_width=False,
        )

    st.markdown(
        "<div style='font-size:0.7rem; color:#9ca3af; "
        "font-family:IBM Plex Mono, monospace; margin-top:0.75rem;'>"
        "Generated by Claude (claude-sonnet-4-6) from filtered ClinicalTrials.gov + openFDA data. "
        "Not for clinical decision-making."
        "</div>",
        unsafe_allow_html=True,
    )
